-- Patent Content Pipeline - D1 Database Schema
-- Run against existing patent-tracker-db (DO NOT create new database)
-- These tables are added alongside the existing patents table

-- Track AI scoring results
CREATE TABLE IF NOT EXISTS patent_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  patent_number TEXT NOT NULL UNIQUE,
  score INTEGER NOT NULL,

  -- Scoring breakdown (1-10 each)
  consumer_relevance INTEGER,
  relatability INTEGER,
  explainability INTEGER,
  visual_appeal INTEGER,

  -- Abstract stored here (fetched from PatentsView during scoring)
  -- NOT in the patents table — that table belongs to patent-tracker
  abstract TEXT,

  -- Plain-English translation generated by scorer (what this patent does for a human)
  -- Shown in admin panel alongside score — invaluable for threshold calibration
  plain_english TEXT,

  -- Haiku reasoning (shown in admin to explain the score)
  reasoning TEXT,

  -- Metadata
  has_diagrams BOOLEAN DEFAULT 0,
  scored_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  approved_for_content INTEGER DEFAULT 0,
  approved_at DATETIME,
  rejected INTEGER DEFAULT 0
);

CREATE INDEX idx_scores_score ON patent_scores(score DESC);
CREATE INDEX idx_scores_approved ON patent_scores(approved_for_content);


-- Track generated content awaiting review
CREATE TABLE IF NOT EXISTS content_queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  patent_number TEXT NOT NULL UNIQUE,
  score INTEGER NOT NULL,

  -- Research data (Google Patents scrape — approved patents only)
  research_summary TEXT,
  research_insights TEXT,
  diagram_urls TEXT,  -- JSON array: ["url1", "url2", "url3"]

  -- Generated content
  caption_twitter TEXT,
  caption_fbli TEXT,
  web_summary TEXT,       -- 2-3 sentence plain-English summary
  web_insights TEXT,      -- 200-300 word insight section
  image_overlay_text TEXT, -- 8-12 word overlay for social image (e.g. "Patent Expired: Vertical Mouse Design")
  social_image_url TEXT,

  -- Website
  url_slug TEXT NOT NULL,
  url_full TEXT NOT NULL,

  -- Scraper health tracking
  scrape_status TEXT DEFAULT 'pending',   -- pending, scraped, failed, blocked
  scrape_attempts INTEGER DEFAULT 0,
  scrape_error TEXT,

  -- Status tracking
  status TEXT DEFAULT 'pending',  -- pending, approved, published, rejected
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  approved_at DATETIME,
  published_at DATETIME
);

CREATE INDEX idx_queue_status ON content_queue(status);
CREATE INDEX idx_queue_created ON content_queue(created_at DESC);


-- Track published content and social posts
CREATE TABLE IF NOT EXISTS published_content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  patent_number TEXT NOT NULL,
  url_slug TEXT NOT NULL,

  -- Social posting tracking
  posted_twitter BOOLEAN DEFAULT 0,
  posted_facebook BOOLEAN DEFAULT 0,
  posted_linkedin BOOLEAN DEFAULT 0,
  posted_at DATETIME,

  -- Manual entry fields (Phase 1)
  post_notes TEXT,

  -- Engagement metrics (Phase 2 - populated via API)
  twitter_likes INTEGER DEFAULT 0,
  twitter_retweets INTEGER DEFAULT 0,
  facebook_likes INTEGER DEFAULT 0,
  facebook_shares INTEGER DEFAULT 0,
  linkedin_likes INTEGER DEFAULT 0,
  linkedin_shares INTEGER DEFAULT 0,
  website_clicks INTEGER DEFAULT 0,

  published_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_published_patent ON published_content(patent_number);
CREATE INDEX idx_published_date ON published_content(published_at DESC);


-- Manage AI prompts (live editing without redeploying workers)
CREATE TABLE IF NOT EXISTS prompts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  prompt_type TEXT NOT NULL,  -- 'scoring' | 'content_generation'
  prompt_text TEXT NOT NULL,
  version INTEGER NOT NULL,
  is_active BOOLEAN DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  notes TEXT
);

CREATE INDEX idx_prompts_type_active ON prompts(prompt_type, is_active);
